### ISSUE TITLE
CircleCI processes

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/NativeScript-Boilerplate#8]
## Expected Behavior

Circleci should be building and deploying without using too many resources.

## Actual/Current Behavior

It appears that 4 Pull requests took over 10,502 CircleCI credits which is quite a large amount for our organization.
![image](https://user-images.githubusercontent.com/398491/96470395-186d5980-11e3-11eb-986a-e0a94cb42718.png)
It also appears to be set up to run 15 simultaneous instances for each PR.
The CircleCI process has been failing for some time on the build step. 

In the build step, the two biggest time consumers are:
* Fetch CocoaPods repository (3.5 minutes)
* Setup system dependencies (9.5 minutes)

## Steps to Reproduce the Problem

  1. Create a PR 
  2. Use up CircleCI credits for each change.

**Comment by michaelachrisco** [comment]
@coreyshuman and @mwallert 

I dont see a `parallelism` setup for the circleci instance and each job states that it is running on `1 / 15 parallel runs` so I believe this job is only running on one instance instead of 15. Nevertheless, the amount of credits is quite high. 

It doesn't appear that the project has had a successful build in the last 90 days. 

As a temp fix, Im going to disable the CircleCI instance for this project so we dont go over on our credits for the rest of the organization.

**Comment by michaelachrisco** [comment]
The CircleCI build have been stopped:
![image](https://user-images.githubusercontent.com/398491/96472190-0b516a00-11e5-11eb-9c66-b8c10e6ae1ae.png)

**Comment by michaelachrisco** [comment]
I believe in order to move forward with this specific CircleCI setup:
1. Use https://circleci.com/docs/2.0/local-cli/ to test out any CircleCI builds (so we dont use credits when testing out failing builds)
2. Get the CircleCI setup to a passing state (at the moment it fails for each job)
3. Reduce the amount of server resources for the current job (Fetch CocoaPods repository and Setup system dependencies). For instance, we may want to use a machine that already contains CocoaPods and most if not all of the dependencies).

**Comment by coreyshuman** [comment]
Thank you for all of these details @michaelachrisco , I appreciate it!
